name: Deploy Splunk Rules
on:
  push:
    paths:
      - 'rules/**/**'

permissions:
  contents: write

jobs:
  first_job:
    runs-on: self-hosted

    steps:      
      - uses: actions/checkout@v4

      - run: pip install pysigma
      - run: python scripts/TechniqueExtractor.py #genera il JSON layer "mitre_navigator_layer.json" nella root dir del repo 

      - run: | #si configura l'identit√† utilizzando il bot di Github
              git config --global user.name 'github-actions[bot]'
              git config --global user.email 'github-actions[bot]@users.noreply.github.com'

              git add mitre_navigator_layer.json
              git commit -m "Auto-update: Aggiornamento MITRE ATT&CK Navigator"
              git push
              
        
        
